version: "2"
services:

  nginxservice:
    image: nginx:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: load
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx/web/:/etc/nginx/web/:ro
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/log/:/var/log/nginx/:rw
##    environment:
##    - NGINX_HOST=tyd.com
##      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon on;']
    
 ##启动,重新构建 docker-compose up --build -d

