version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-zk
    ports:
      - "2181:2181"
    environment:
      ZOO_MAX_CLIENT_CNXNS:10000
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_MAX_CLIENT_CNXNS: 10000
      ZOO_SYNC_LIMIT: 5
      ZOO_INIT_LIMIT: 10
      ZOO_TICK_TIME: 2000
      TZ: Asia/Shanghai

  kafka:
   # build: .
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

## https://hub.docker.com/r/wurstmeister/kafka
## docker-compose -f /opt/kafka_install/docker-compose.yml up -d
