version: "3"
services:

  dubboservice:
    image: tomcat:8
    container_name: dubboadmin
    user: root
    volumes:
      - /opt/dubbo/dubbo.war:/usr/local/tomcat/webapps/dubbo.war:rw
      - /opt/dubbo/dubbo.properties:/root/dubbo.properties:rw
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
    restart: always
## docker-compose up -d
