version: '3'

services:
  mongodb:
    image: mongo:3.4.1
    volumes:
      - './data/db:/data/db'
    networks:
      - easy-mock
    restart: always

  redis:
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      - './data/redis:/data'
    networks:
      - easy-mock
    restart: always

  web:
    image: easymock/easymock:1.6.0
    command: /bin/bash -c "npm start"
    ports:
      - 7300:7300
    volumes:
      # Error: EACCES: permission denied, open 'logs/2020-04-08-info.log'
      # chmod 777 /var/logs/easy-mock
      - '/var/logs/easy-mock/:/home/easy-mock/easy-mock/logs'
      # - './production.json:/home/easy-mock/easy-mock/config/production.json'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock: